// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRpIRH5oP2jfDoBN9YfioKfWY08zKhpxM',
    appId: '1:778345751726:web:8bdf6adb622563b831393f',
    messagingSenderId: '778345751726',
    projectId: 'patientwatch-ea518',
    authDomain: 'patientwatch-ea518.firebaseapp.com',
    storageBucket: 'patientwatch-ea518.firebasestorage.app',
    measurementId: 'G-MNY5FZKJMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfcuQeP_LIdHmKA2lfYySo9OE_gFbqaU8',
    appId: '1:778345751726:android:a6832a76f069668b31393f',
    messagingSenderId: '778345751726',
    projectId: 'patientwatch-ea518',
    storageBucket: 'patientwatch-ea518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKHkUjVnfgOb2keN_-f4U06L5w2wh31xI',
    appId: '1:778345751726:ios:613a8c4177f13a5831393f',
    messagingSenderId: '778345751726',
    projectId: 'patientwatch-ea518',
    storageBucket: 'patientwatch-ea518.firebasestorage.app',
    iosBundleId: 'com.example.patientWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKHkUjVnfgOb2keN_-f4U06L5w2wh31xI',
    appId: '1:778345751726:ios:613a8c4177f13a5831393f',
    messagingSenderId: '778345751726',
    projectId: 'patientwatch-ea518',
    storageBucket: 'patientwatch-ea518.firebasestorage.app',
    iosBundleId: 'com.example.patientWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRpIRH5oP2jfDoBN9YfioKfWY08zKhpxM',
    appId: '1:778345751726:web:0f9ccce16cc9e3c531393f',
    messagingSenderId: '778345751726',
    projectId: 'patientwatch-ea518',
    authDomain: 'patientwatch-ea518.firebaseapp.com',
    storageBucket: 'patientwatch-ea518.firebasestorage.app',
    measurementId: 'G-Q026VXKZ7Z',
  );
}
